### PR TITLE
DSi rom support

### PR DESCRIPTION
**Pull request by MetLob**
DSi Support:
+ DSi header support
+ Banner version supports
+ arm9i+arm7i descripted supports
+ All hashes recalc

Other fix:
+ Fix Overlays Writing (if resierved = 0 or size)
+ Fix FAT Writing for Overlays (name.StartsWith("overlay") can be for a not overlays file then we got invalid FAT)

Build for tests: https://drive.google.com/file/d/1WbKOqEukgjSUKDCOs9n8kts-l_euHS0a/view

### CODE REVIEW

**Comment by MetLob** [comment]
This is my old works from winter 2017-2018. Sorry for hiatus.
This branch tested on russian translation project of Shantae (DSi):
http://coreline.su/metlob-ft-friends/#projects/15/

and Famicom Wars (English patch):
https://drive.google.com/open?id=1A5Mmz8qZQqLqJD5cLOVtoHyYxLjacznU

**Comment by MetLob** [comment]
Also I added Tools\Arm9 Compress+Decompress for using this in DSi mode (for hash recalc).
But this didn't use in the standatd DS mode.

**Comment by RocketRobz** [comment]
@MetLob I have a question.
Does this fix the hash for the DS/DSi headers?
I changed the DSiWare ROM's title ID in the DS and DSi extended headers, and wouldn't run, as a result.

**Comment by MetLob** [comment]
@RocketRobz 
If title ID has been changed then all hashes must recalc.

**Comment by MetLob** [comment]
@RocketRobz
Hi. I fixed this. It was Secure Area problem. 
GameCode is key for SA encryption and I had to re-encrypt SA section for encrypted arm9.bin

**Comment by pleonex** [comment]
I appreciate the effort to add support for DSi. I know of firsthand that this is not easy.
Unfortunately I don't have plans to maintain Tinke anymore as I've been working on a replacement for several years already (SceneGate). This is a big PR that introduces many changes and I don't feel comfortable merging without proper review and testing, that it's extremely hard and time consuming due to the old and not so good architecture of Tinke.

I would be happy to see a fork of Tinke adding this content.

PS: I just realized about your implementation to decrypt ARMi and recalculate all hashes. I spent many hours trying to implement something similar from raw specs of GbaTek and guessing how to do in [Ekona](https://github.com/SceneGate/Ekona/). Happy to see someone else trying to do the same :smile:

**Pull request closed without merging**
