### PR TITLE
Layton: update to version 0.6

### PR DESCRIPTION
**Pull request by MetLob**
Added image and animation import
Added text editor for text formats in NAZO folder (Layton 2)

### CODE REVIEW

**Comment by MetLob** [comment]
I wanted create pull request with Layton plugin files only... I do not understand how to do it.

**Comment by pleonex** [comment]
Don't worry, the problem is that since in your branch you have the changes for the 4x4 texture compressor too, it adds these commits too.  So I will merge first the other pull request so after that, this pull request will have only the layton changes.

**Comment by MrJPGames** [comment]
This is a really great addition and I'm very thankful! However it seems that after importing any images (ani or non-ani) it always corrupts the header area which makes it unable to run in emulators and on real hardware with a flashcard, but it does still detect everything properly in Tinke itself (when reopening the exported rom). Though it seems different from issue #41 as this rom has not been trimmed.

Hopefully this was helpful, or maybe if I'm doing something wrong could you please inform me.

Thank You!

**Comment by MrJPGames** [comment]
So after the fix for issue #41 it saves correctly. But images do not appear in the game at all (they're totally black) And in Tinke they are transparent (and probably in the game as well but there the background was black). I was replacing bg images with replace palette turned on.

**Comment by MetLob** [comment]
Images in Layton's *.arc files can be imported with "Swap palette" options only.
Because not all palettes of files used in the game. For example:
File1.arc with palette1
File2.arc with palette2
Colors in palette1 = palette2
Game used only palette1 for File1 and File2
If you change palette2 by "Replace" option then File2.arc will be opening in game with errors.

**Comment by MetLob** [comment]
For BG Images with "Replace palette" options.
This fixing by Click on Button "Set tranparency" after import.

**Comment by MetLob** [comment]
For **Changed palette** i must to put first transparent color to the palette. Or user can press the button after import. But in plugin namespace I can't see, what palette was loaded - swapped or changed. 
@pleonex, сan I skip this fix?

**Comment by MrJPGames** [comment]
The Set transparency fix doesn't work. However when turining on Map Compression it does work, but with not quite the result you want. I think it's easier to show you the result. (Note that inside of Tinke the image stays looking correctly, only in the actual game do the graphics look messed up):
glitchy_screen

**Comment by MetLob** [comment]
Can you send this file (redrawed png or bmp) to me for testing?

**Comment by MrJPGames** [comment]
image
(The result in game, I changed the image since the last post so that's why I'm including it here)
And here is the original file:
ara_top arc

**Comment by MetLob** [comment]
In specified files game code overrides some colors of the palette.
For problem files try to reduce colors count in the Photoshop or others image editors.

For example, this file (ara_top.arc) has 64 as default colors count.
But in your redrawed sample using 252 unique colors.
Try reducing this to 120 or 64 using Floyd-Dithering for best quality.

I try to implement this in later.

**Comment by MetLob** [comment]
Hi! Test this commit please.
Now in the "Replace palette" mode the user is asked to select if the new palette has more colors than original:
"Force swaping at original palette?"

If you click the "Yes" button then palette will be swaped to the original.
If "No" - the image will be saved with the new palette (as before).

**Comment by MrJPGames** [comment]
Thank you, this seems to fix the issues I was having. It does still need map compression to be on, but it works! Also, and this is not a bug, but what is the easiest way to fix the "too many colors" error, right now I just play with the settings in Paint.net until it spits out an image with the supported amount of colors.

**Comment by pleonex** [comment]
Amazing work! Thank you @MetLob for implementing and @MrJPGames for testing. I want to review the changes as soon as possible and release a new version.

Regarding how to reduce the number of colors, I know how to do it with Gimp:
1. Open the image.
2. Go to *Image->Mode->Indexed...*
  * If it's indexed already, click first on *Image->Mode->RGB* and then again in Indexed.
3. Select *Generate optimum palette* and set the maximum number of colors you want in the image. Then just click Convert and that is.

**Comment by MetLob** [comment]
Implement PLZ (PCK2) file packing

**Pull request merged**
